#!/bin/bash
clear
REPO="https://raw.githubusercontent.com/zhets/project/main/"
wget -O /etc/xray/config.json "${REPO}xray/config.json" >/dev/null 2>&1
sed -i "s/xxx/${domain}/g" /etc/nginx/conf.d/xray.conf
curl ${REPO}ssh/nginx.conf > /etc/nginx/nginx.conf
systemctl daemon-reload
systemctl start nginx
systemctl enable --now nginx
systemctl restart nginx
systemctl status nginx
