#!/bin/bash
NC='\e[0m'
MYIP=$(curl -sS ipv4.icanhazip.com)
clear
Repo1="https://raw.githubusercontent.com/zhets/izin/main/"
export MYIP=$( curl -s https://ipinfo.io/ip/ )
SELLER=$(curl -sS ${Repo1}ip | grep $MYIP | awk '{print $2}')
Exp100=$(curl -sS ${Repo1}ip | grep $MYIP | awk '{print $3}')
data_ip="https://raw.githubusercontent.com/zhets/izin/main/ip"
d2=$(date -d "$date_list" +"+%s")
d1=$(date -d "$Exp" +"+%s")
dayleft=$(( ($d1 - $d2) / 86400 ))

#########################
[[ ! -f /usr/bin/git ]] && apt install git -y &> /dev/null
# COLOR VALIDATION
clear
y='\033[1;93m'
c="\033[0;36m"
g="\e[92;1m"
r="\033[1;31m"
NC='\e[0m'
gray="\e[1;30m"
Blue="\033[1;36m"
GREEN='\033[0;32m'
grenbo="\033[1;95m"
yell='\e[33m'
BGX="\033[42m"
END='\e[0m'
bc="\e[5;36m"
ungu='\033[0;35m'
Green_background="\033[42;37m"
Red_background="\033[41;37m"
Suffix="\033[0m"

AKTIF="VERIFIED"
TOKEN="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"
REPO="https://github.com/zhets/izinsc.git"
EMAIL="Mfvstore1@gmail.com"
USER="zhets"

function lane() {
echo -e "${bc} ————————————————————————————————————————${NC}"
}

function LOGO() {
echo -e ""
lane
echo -e "${ungu}            Fvstore Tunneling            "
lane
echo -e ""
}

function register() {
echo -e "${ungu}               Register IP              ${Suffix}"
}

function Credit_Fvstore() {
sleep 1
echo -e "" 
lane
echo -e "${ungu}      Terimakasih sudah menggunakan-"
echo -e "         Script Credit by FvSTORE"
lane
echo -e ""
exit 0
}

add-ip() {
TIMES="10"
CHATID="5548605787"
KEY="6831214064:AAFk_Qmx4q_Y2cPEvaoM0q3ux8Dlk3r_Jbk"
URL="https://api.telegram.org/bot$KEY/sendMessage"


today=`date -d "0 days" +"%Y-%m-%d"`
git clone ${REPO} /root/izinsc/ &> /dev/null
clear
echo -e "MASUKAN IP VPS YANG BELUM DI DAFTAR !"
echo -e ""
read -p "Input IP Address : " ip
CLIENT_EXISTS=$(grep -w $ip /root/izinsc/ip | wc -l)
if [[ ${CLIENT_EXISTS} == '1' ]]; then
echo "IP Already Exist !"
exit 0
fi
echo -e ""
   # read -p "  Input Username IP (Example : Fvstore) : " name
name=F6EPQtYeJ3DmRZaL`</dev/urandom tr -dc A-Z0-9 | head -c4`
echo -e ""
clear
echo -e " ${r} Sett Waktu Expired${NC}"
echo -e "  ${y} 1.${NC}${c} 30 Days${NC}"
echo -e "  ${y} 2.${NC}${c} 60 Days${NC}"
echo -e "  ${y} 3.${NC}${c} 90 Days${NC}"
echo -e "  ${y} 4.${NC}${c} Lifetime${NC}"
echo -e "  ${y} 5.${NC}${c} Custom Expiration Date${NC}"
echo -e ""
read -p "Select Number 1 - 5 : " exp

if [[ ${exp} == '1' ]]; then
exp2=`date -d "30 days" +"%Y-%m-%d"`
echo "### ${name} ${exp2} ${ip}" >> /root/izinsc/ip
elif [[ ${exp} == '2' ]]; then
exp2=`date -d "60 days" +"%Y-%m-%d"`
echo "### ${name} ${exp2} ${ip}" >> /root/izinsc/ip
elif [[ ${exp} == '3' ]]; then
exp2=`date -d "90 days" +"%Y-%m-%d"`
echo "### ${name} ${exp2} ${ip}" >> /root/izinsc/ip
elif [[ ${exp} == '4' ]]; then
exp2=`date -d "360 days" +"%Y-%m-%d"`
echo "### ${name} ${exp2} ${ip}" >> /root/izinsc/ip
elif [[ ${exp} == '5' ]]; then
read -p "Input Expired Days : " exp11
exp2=`date -d "$exp11 days" +"%Y-%m-%d"`
echo "### ${name} ${exp2} ${ip}" >> /root/izinsc/ip
fi
cd /root/izinsc
git config --global user.email "${EMAIL}" &> /dev/null
git config --global user.name "${USER}" &> /dev/null
rm -rf .git &> /dev/null
git init &> /dev/null
git add . &> /dev/null
git commit -m register &> /dev/null
git branch -M main &> /dev/null
git remote add origin https://github.com/zhets/izinsc
git push -f https://${TOKEN}@github.com/${USER}/izinsc.git &> /dev/null
rm -rf /root/izinsc
clear
sleep 1
echo "  Registering IP Address..."
sleep 1
echo "  Processing..."
sleep 1
echo "  Done!"
sleep 1
clear
TEXT="
<code>───────────────────────────</code>
<code>   SUCCESS  REGISTERED IP VPS</code>
<code>───────────────────────────</code>
<code>USERNAME       : $name</code>
<code>IP Address     : $ip</code>
<code>Registered On  : $today</code>
<code>Expired On     : $exp2</code>
<code>───────────────────────────</code>
"
lane
echo -e "${g}       SUCCES ADD IP VPS      $NC"
lane
echo -e "${y}  USERNAME   :${NC}${yell} $name"
echo -e "${y}  IP ADDRESS :${NC}${yell} $ip"
echo -e "${y}  REGISTERED :${NC}${yell} $today"
echo -e "${y}  EXPIRED ON :${NC}${yell} $exp2"
lane
Credit_Fvstore
echo -e ""
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

del-ip() {
TIMES="10"
CHATID="5548605787"
KEY="6831214064:AAFk_Qmx4q_Y2cPEvaoM0q3ux8Dlk3r_Jbk"
URL="https://api.telegram.org/bot$KEY/sendMessage"

rm -rf /root/izin
git clone ${REPO} /root/izinsc/ &> /dev/null
clear
echo ""
lane
echo -e "$g          LIST IP VPS          $NC"
lane
grep -E "^###" "/root/izinsc/ip" | cut -d ' ' -f 2-6 | column -t | sort | uniq
grep -E "^#&"  "/root/izinsc/ip" | cut -d ' ' -f 2-6 | column -t | sort | uniq
lane

read -p "Input IP Address To Delete : " ipdel
name=$(cat /root/izinsc/ip | grep $ipdel | awk '{print $2}')
exp=$(cat /root/izinsc/ip | grep $ipdel | awk '{print $3}')
if [[ ${exp} == 'Lifetime' ]]; then
sed -i "/^#&   $name   $exp $ipdel/,/^},{/d" /root/izinsc/ip
else
sed -i "/^### $name $exp $ipdel/,/^},{/d" /root/izinsc/ip
fi
cd /root/izinsc
git config --global user.email "${EMAIL}" &> /dev/null
git config --global user.name "${USER}" &> /dev/null
rm -rf .git &> /dev/null
git init &> /dev/null
git add . &> /dev/null
git commit -m register &> /dev/null
git branch -M main &> /dev/null
git remote add origin https://github.com/zhets/izinsc
git push -f https://${TOKEN}@github.com/zhets/izinsc.git &> /dev/null
rm -rf /root/izinsc
clear
sleep 1
echo "  Delete IP Address..."
sleep 1
echo "  Processing..."
sleep 1
echo "  Done!"
sleep 1
clear
TEXT1="
<code>───────────────────────────</code>
<code>    SUCCESS DELETE IP VPS</code>
<code>───────────────────────────</code>
<code>USERNAME       : $name</code>
<code>IP Address     : $ipdel</code>
<code>Expired On     : $exp</code>
<code>───────────────────────────</code>
"
lane
echo -e "${g}       DONE DELETE IP VPS      $NC"
lane
echo -e "${y}  USERNAME   :${NC}${yell} $name"
echo -e "${y}  IP ADDRESS :${NC}${yell} $ipdel"
echo -e "${y}  EXPIRED ON :${NC}${yell} $exp"
lane
Credit_Fvstore
echo -e ""
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT1&parse_mode=html" $URL >/dev/null
}

renew-ip() {
TIMES="10"
CHATID="5548605787"
KEY="6831214064:AAFk_Qmx4q_Y2cPEvaoM0q3ux8Dlk3r_Jbk"
URL="https://api.telegram.org/bot$KEY/sendMessage"

rm -rf /root/izin
git clone ${REPO} /root/izinsc/ &> /dev/null
clear
lane
echo -e "${g}        RENEW IP VPS      $NC"
lane
grep -E "^###" "/root/izinsc/ip" | cut -d ' ' -f 2-6 | column -t | sort | uniq
lane
echo ""
read -p "  Input IP Address To Renew : " ipdel
read -p "  Input Days  : " days
name=$(cat /root/izinsc/ip | grep $ipdel | awk '{print $2}')
exp=$(cat /root/izinsc/ip | grep $ipdel | awk '{print $3}')
now=$(date +%Y-%m-%d)
d1=$(date -d "$exp" +%s)
d2=$(date -d "$now" +%s)
exp2=$(( (d1 - d2) / 86400 ))
exp3=$(($exp2 + $days))
exp4=`date -d "$exp3 days" +"%Y-%m-%d"`
sed -i "s/### $name $exp $ipdel/### $name $exp4 $ipdel/g" /root/izin/ip
cd /root/izinsc
git config --global user.email "${EMAIL}" &> /dev/null
git config --global user.name "${USER}" &> /dev/null
rm -rf .git &> /dev/null
git init &> /dev/null
git add . &> /dev/null
git commit -m register &> /dev/null
git branch -M main &> /dev/null
git remote add origin https://github.com/zhets/izinsc
git push -f https://${TOKEN}@github.com/zhets/izinsc.git &> /dev/null
rm -rf /root/izinsc
clear
sleep 1
echo "  Renew IP Address..."
sleep 1
echo "  Processing..."
sleep 1
echo "  Done!"
sleep 1
clear
TEXT2="
<code>───────────────────────────</code>
<code>    SUCCESS RENEW  IP VPS</code>
<code>───────────────────────────</code>
<code>USERNAME       : $name</code>
<code>IP Address     : $ipdel</code>
<code>Expired On     : $exp4</code>
<code>───────────────────────────</code>
"
echo ""
lane
echo -e "${g}      DONE RENEW IP VPS      $NC"
lane
echo -e "${y}  USERNAME   :${NC}${yell} $name"
echo -e "${y}  IP ADDRESS :${NC}${yell} $ipdel"
echo -e "${y}  EXPIRED ON :${NC}${yell} $exp4"
lane
Credit_Fvstore
echo -e ""
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT2&parse_mode=html" $URL >/dev/null
}

clear
LOGO
register
lane
echo -e " $g 1.$NC ${c}ADD IP VPS "$NC     
echo -e " $g 2.$NC ${c}DELETE IP VPS"$NC
echo -e " $g 3.$NC ${c}RENEW IP VPS"$NC
echo -e " $g x.$NC ${c}Back To menu"$NC
lane
echo ""
read -p " Select From Options [1 - 3 or x] : " menu
case $menu in
1 | 01)
clear
add-ip
;;
2 | 02)
clear
del-ip
;;
3 | 03)
clear
renew-ip
;;
4 | 04)
menu
;;
*)
exit
;;
esac
